scrapings/urls.py
from django.urls import path
from . import views

app_name = 'scrapings'

urlpatterns = [
    path('', views.citizen, name='citizen'),
    path('ntv/', views.ntv, name='ntv'),
    path('ktn/', views.ktn_news, name='ktn_news'),
    path('k24/', views.k24, name='k24'),
]

taifa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrapings.urls', namespace='scrapings')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    img = models.CharField(max_length=200, blank=True, null=True)


    def __str__(self):
        return self.title

scrapings/models.py
from django.db import models
# title = scrapy.Field()
    # content = scrapy.Field()
    # author = scrapy.Field()
    # image = scrapy.Field()
    # published_on = scrapy.Field()
    # summary = scrapy.Field()
    # url = scrapy.Field()
    # project = scrapy.Field()
    # spider = scrapy.Field()
    # server = scrapy.Field()
    # data = scrapy.Field()


class CitizenModel(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    published_on = models.CharField(max_length=255, null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    url = models.CharField(blank=True, null=True, max_length=255)
    timestamp = models.CharField(blank=True, null=True, max_length=255)
    spider = models.CharField(blank=True, null=True, max_length=255)
    domain = models.CharField(blank=True, null=True, max_length=255)

    class Meta:
        verbose_name = 'Citizen Articles'
        verbose_name_plural = 'Citizen Articles'

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ['email', 'username']


class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = ['email', 'username']

posts/views.py
from django.shortcuts import render

# Create your views here.

scrapings/views.py
from django.shortcuts import render
from posts.models import Post
from scrapings.models import CitizenModel


def home(request):
    context = {
        'title': 'citizen should be the title'
    }
    return render(request, 'base.html', context)


def citizen(request):
    cleaned_posts = []
    posts = CitizenModel.objects.filter('-id')[:20]
    context = {
        'title': 'citizen',
        'posts': posts,
        'something': 'another thing all together'
    }
    return render(request, 'citizen/index.html', context)


def ntv(request):
    context = {
        'title': 'ntv'
    }
    return render(request, 'ntv/index.html', context)


def ktn_news(request):
    context = {
        'title': 'ktn news'
    }
    return render(request, 'ktn_news/index.html', context)


def k24(request):
    context = {
        'title': 'k24'
    }
    return render(request, 'k24/index.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taifa |  {% block title %} {{title}} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Taifa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav mr-auto">
                
               
              </ul>
              <span class="navbar-text">
                
              </span>
            </div>
          </nav>
    </header>
    <main>
        <div class="container">
            <ul class="nav nav-tabs">
                <li class="nav-item ">
                  <a class="nav-link active" href="{% url 'scrapings:citizen' %}">citizen</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'scrapings:ntv' %}">ntv</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'scrapings:k24' %}">k24</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'scrapings:ktn_news' %}">ktn news</a>
                </li>
              </ul>
              {% block content %}

              {% endblock %}

        </div>
        
    </main>
    

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/citizen/index.html
{% include 'base.html' %}
{% block title %} {% endblock %}
{% block content %}




  <div class="post">
    <h2>
    {{post.title}}
    </h2>
    <p>
    {{post.content}}
    </p>
</div>



    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% for post in posts %}
                <div class="card card-custom">
                    <!-- <img class="card-img-top card-img" src="{{ post.image }}" alt="article image" style="max-height: 100px;"> -->
                    <div class="card-body">
                      <h5 class="card-title">{{ post.title }}</h5>
                      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                    <div class="card-footer custom-cardfooter">
                      <small class="text-muted">By:  {{post.author}}</small>
                      <small class="text-muted text-right">Published On  {{post.published_on}}</small>
                    </div>
                  </div>
                    
                {% endfor %}

            </div>

        
            <div class="col-md-4 aside-div">
                    <h3>Citizen Twitter feed @citizenTv_ke </h3>

            </div>
        </div>
    </div>
    

{% endblock %}

templates/k24/index.html
{% include 'base.html' %}
{% block title %}  {% endblock %}
{% block content %}
<div class="container">
    <h2>Welcome to k24</h2>
</div>
    

{% endblock %}

templates/ktn_news/index.html
{% include 'base.html' %}
{% block title %}  {% endblock %}
{% block content %}
<div class="container">
    <h2>Welcome to ktn news</h2>
</div>
   

{% endblock %}

templates/ntv/index.html
{% include 'base.html' %}
{% block title %} {% endblock %}
{% block content %}
    <div class="container">
        <h2>Welcome to ntv</h2>
    </div>
    

{% endblock %}